name: dotnet package

on: [pull_request]

jobs:
  build-and-test:
    name: Build and Test the Solution

    runs-on: ubuntu-latest
# What does this do?
#    strategy:
#      matrix:
#        dotnet-version: [ '3.1.x', '6.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - uses: actions/github-script@v6
        name: Add a comment to the PR
        if: ${{ failure() }}
        with:
          github-token: ${{ secrets.WS_14202_PRCOMMENTINGFROMACTIONS }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚨 - Changes in this PR are incompatible with the new Hot Chocolate GraphQL engine.'
            })
            