name: Run Schema Comparison Test
on: [pull_request]
env:
  DOTNET_INSTALL_DIR: "./.dotnet"
jobs:
  build:
    name: Build the Solution
    runs-on: ubuntu-latest
# What does this do?
#    strategy:
#      matrix:
#        dotnet-version: [ '3.1.x', '6.0.x' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore --nologo
      - uses: actions/github-script@v6
        name: Add a Warning comment to the PR
        if: ${{ failure() }}
        with:
          github-token: ${{ secrets.WS_14202_PRCOMMENTINGFROMACTIONS }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## 🚨 These changes break `dotnet build`'
            })
  test:
    name: Run the Schema Comparison Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: dotnet test $DOTNET_INSTALL_DIR --no-restore --verbosity normal --filter FullyQualifiedName=GitHubActions.Tests.Tests.Test1
      - uses: actions/github-script@v6
        name: Add a Warning comment to the PR
        if: ${{ failure() }}
        with:
          github-token: ${{ secrets.WS_14202_PRCOMMENTINGFROMACTIONS }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ These changes are incompatible with the HotChocolate GraphQL engine'
            })
      - uses: actions/github-script@v6
        name: Add a Success comment to the PR
        if: ${{ success() }}
        with:
          github-token: ${{ secrets.WS_14202_PRCOMMENTINGFROMACTIONS }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '### ✅ These changes are fully compatible with the HotChocolate GraphQL engine  🎉'
            }) 